from typing import Annotated, Sequence, TypedDict, List

from langchain_core.messages import BaseMessage
import operator


class AgentState(TypedDict):
# Task is user input 
    task: str
# Plan by planner agent 
    plan: str
# Generated by Generator Agent
    generated: str
# Documents by Researcher Agent 
    content: List[str]
# Grading score by Grader Agent
    grading_score: int
# Final review & hellucination score by Reviewer Agent
    final_review: str
    hellucination_score: int
# Search number and max searches for Researcher Agent
    search_number: int
    max_searches: int
# Amount of generations throughout workflow with a limit 
    revision_number: int
    max_revisions: int
# Use saved data if available
    use_saved_data: bool
    history: List
    thead_id: str
    # id: str
    # # messages: Annotated[Sequence[BaseMessage], operator.add]
    # sender: str
    # channel_values: dict
    # v: int
    # ts: str
    # channel_versions: dict
    # versions_seen: dict
    # pending_sends: List[str]
    
    